In [2]:
print("hello world")

hello world


In [3]:
# creating nump/n-d arrays
import numpy as np

In [4]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr3=np.zeros((2,3))
arr3 #initializing array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
arr4=np.ones((2,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
arr5=np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
arr6=np.arange(10)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr6=np.arange(5,15)
arr6

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
arr7=np.arange(5,16,2) #2-2 nums dega
arr7

array([ 5,  7,  9, 11, 13, 15])

In [13]:
arr8=np.linspace(10,20,10)
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [14]:
arr9=arr7.copy()
arr9

array([ 5,  7,  9, 11, 13, 15])

In [15]:
arr1.shape #prints no of rows and column

(5,)

In [16]:
arr5.shape 

(5, 5)

In [17]:
arr9=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr9

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [18]:
arr9.shape #prints dimension of array

(2, 2, 2)

In [19]:
arr9.ndim #Each extra [ = one more dimension

3

In [20]:
print(arr2)
print(f"Dimension of array is:{arr2.ndim}" )

[[1 2 3]
 [4 5 6]]
Dimension of array is:2


In [21]:
arr1.size # num of values inside an array

5

In [22]:
arr9.size

8

In [23]:
arr9.itemsize #number of bytes used by ONE element

8

In [24]:
arr8.itemsize

8

In [25]:
arr8.dtype

dtype('float64')

In [26]:
arr9.dtype 

dtype('int64')

In [27]:
arr9.astype('float') #converts into mentioned data type

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

In [28]:
"""
Lists vs Arrays
 -array is faster than list
 -more convinient
 -occupies less memory
"""

'\nLists vs Arrays\n -array is faster than list\n -more convinient\n -occupies less memory\n'

In [29]:
lista=range(100)
arr11=np.arange(100)

In [30]:
import sys 

In [31]:
print(sys.getsizeof(87)*len(lista))

2800


In [32]:
print(arr11.itemsize*arr11.size) # array takes comparatively less memory than lists

800


In [33]:
import time

In [34]:
x=range(10000000)
y=range(10000000,20000000)

start_time=time.time()

z=[x+y for x,y in zip(x,y)]
print(time.time()-start_time)

3.014086961746216


In [35]:
a=np.arange(10000000)
b=np.arange(10000000,20000000)
start_time=time.time()
c=a+b
print(time.time()-start_time)     #array is faster than lists

0.059099435806274414


In [36]:
"""
Indexing, Slicing and Iteration
"""

'\nIndexing, Slicing and Iteration\n'

In [37]:
arr12=np.arange(24).reshape(6,4) 
#6 rows and 4 column ka 0 to 23 ka array banega
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [38]:
arr12.ndim

2

In [39]:
arr1[2:4]

array([3, 4])

In [40]:
arr12[2] #index 2 ki values

array([ 8,  9, 10, 11])

In [41]:
arr12[:,2] #to print only columns

array([ 2,  6, 10, 14, 18, 22])

In [42]:
arr12[3,1:3] #comma ke pehle row slicing and badme column slicing

array([13, 14])

In [43]:
arr12[4:,2:]

array([[18, 19],
       [22, 23]])

In [44]:
for i in arr12:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [45]:
for i in np.nditer(arr12):
    print(i) #to print every item use this nump func    

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [46]:
"""
Numpy Operations
"""

'\nNumpy Operations\n'

In [47]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([4,5,6,7,8,9])

In [48]:
arr1-arr2

array([-3, -3, -3, -3, -3, -3])

In [49]:
arr1*arr2

array([ 4, 10, 18, 28, 40, 54])

In [50]:
arr1*2 # scalar multiplication

array([ 2,  4,  6,  8, 10, 12])

In [51]:
arr2>3 

array([ True,  True,  True,  True,  True,  True])

In [52]:
arr3=np.arange(6).reshape(2,3)
arr4=np.arange(6,12).reshape(3,2)
print(arr3,"\n""\n", arr4)

[[0 1 2]
 [3 4 5]] 

 [[ 6  7]
 [ 8  9]
 [10 11]]


In [53]:
arr3.dot(arr4) # dot func does matrix multiplication

array([[ 28,  31],
       [100, 112]])

In [54]:
arr1.dot(arr2)

np.int64(154)

In [55]:
#arr1.dot(arr3) # m x n match nahi hua

In [56]:
print(arr4)
arr4.max() #prints max value

[[ 6  7]
 [ 8  9]
 [10 11]]


np.int64(11)

In [57]:
arr4.min()

np.int64(6)

In [58]:
arr4.min(axis=0) # column wise min value

array([6, 7])

In [59]:
arr4.min(axis=1) # row wise min value

array([ 6,  8, 10])

In [60]:
arr4.sum()

np.int64(51)

In [61]:
arr4.sum(axis=0) # column wise sum

array([24, 27])

In [62]:
"""
Mean: Average of all values (sum ÷ count)
Median: Middle value after sorting the data
Standard deviation (std): How spread out values are from the mean
"""

'\nMean: Average of all values (sum ÷ count)\nMedian: Middle value after sorting the data\nStandard deviation (std): How spread out values are from the mean\n'

In [63]:
arr4.mean() #unary operations

np.float64(8.5)

In [64]:
arr4.std() # standard deviation

np.float64(1.707825127659933)

In [65]:
np.sin(arr4)

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

In [66]:
print(np.median(arr4)) # universal operations
"""
the reason we are calling functions in a different way
is oops concept where func needs object and somewhere doesn't
"""

8.5


"\nthe reason we are calling functions in a different way\nis oops concept where func needs object and somewhere doesn't\n"

In [67]:
np.exp(arr4) #exponent

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])

In [68]:
"""
Reshaping Numpy arrays
"""

'\nReshaping Numpy arrays\n'

In [69]:
#Ravel function
arr4.ndim

2

In [70]:
arr4.ravel() #higher dimension array ko 1d kar deta hai


array([ 6,  7,  8,  9, 10, 11])

In [71]:
#reshape

In [72]:
#Transpose

In [73]:
arr4.transpose() # row ka column, column ka row

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [74]:
# Stacking

In [75]:
arr5=np.arange(12,18).reshape(2,3)
arr5

array([[12, 13, 14],
       [15, 16, 17]])

In [76]:
np.hstack((arr3,arr5)) #horizontally stacking

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17]])

In [77]:
np.vstack((arr3,arr5)) # vertical stacking

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [12, 13, 14],
       [15, 16, 17]])

In [78]:
# Splitting
np.hsplit(arr5,3) #vertical splitting

[array([[12],
        [15]]),
 array([[13],
        [16]]),
 array([[14],
        [17]])]

In [79]:
np.vsplit(arr5,2) # horizontal splitting

[array([[12, 13, 14]]), array([[15, 16, 17]])]

In [80]:
# fancy indexing

In [81]:
arr8=np.arange(24).reshape(6,4)
arr8

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [82]:
arr8[0::2] #isme 1 row chodhke dusra print kia hai by defining 0 se last row tak and 2 = 1 ka gap

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [83]:
#another way
arr8[[0,2,4]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [84]:
# Indexing with Boolean arrays

In [85]:
arr=np.random.randint(low=1,high=100,size=20).reshape(4,5)
arr

array([[ 4, 20,  3, 69,  4],
       [18, 35, 12, 99, 36],
       [24, 83, 14, 32, 83],
       [32, 21, 17, 96,  9]], dtype=int32)

In [86]:
arr[arr>50] # Indexing with Boolean arrays

array([69, 99, 83, 83, 96], dtype=int32)

In [87]:
#boht saare operations run kar skte ho
arr[(arr>50) & (arr%2 != 0)] #boolean operators be bitwise and lagate ho

array([69, 99, 83, 83], dtype=int32)

In [88]:
arr[(arr>50) & (arr%2 != 0)]=0 # jo bhi numbers 50 se greater hai and odd hai woh zero ho jaenge
arr

array([[ 4, 20,  3,  0,  4],
       [18, 35, 12,  0, 36],
       [24,  0, 14, 32,  0],
       [32, 21, 17, 96,  9]], dtype=int32)

In [89]:
# Plotting graphs using numpy

In [90]:
x=np.linspace(-40,40,100) # creating numpy array -40 se 40 tak 100 numbers honge
x

array([-40.        , -39.19191919, -38.38383838, -37.57575758,
       -36.76767677, -35.95959596, -35.15151515, -34.34343434,
       -33.53535354, -32.72727273, -31.91919192, -31.11111111,
       -30.3030303 , -29.49494949, -28.68686869, -27.87878788,
       -27.07070707, -26.26262626, -25.45454545, -24.64646465,
       -23.83838384, -23.03030303, -22.22222222, -21.41414141,
       -20.60606061, -19.7979798 , -18.98989899, -18.18181818,
       -17.37373737, -16.56565657, -15.75757576, -14.94949495,
       -14.14141414, -13.33333333, -12.52525253, -11.71717172,
       -10.90909091, -10.1010101 ,  -9.29292929,  -8.48484848,
        -7.67676768,  -6.86868687,  -6.06060606,  -5.25252525,
        -4.44444444,  -3.63636364,  -2.82828283,  -2.02020202,
        -1.21212121,  -0.4040404 ,   0.4040404 ,   1.21212121,
         2.02020202,   2.82828283,   3.63636364,   4.44444444,
         5.25252525,   6.06060606,   6.86868687,   7.67676768,
         8.48484848,   9.29292929,  10.1010101 ,  10.90

In [91]:
x.size

100

In [92]:
y=np.sin(x)
print(y.size)

100


In [93]:
# Broadcasting is the ability of numpy to perform arithmetic operations on dissimilar array

In [94]:
#Scenario 1
a1=np.arange(8).reshape(2,4)
a2=np.arange(8,16).reshape(2,4)

print(a1)
print(a2)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [95]:
a1+a2

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [96]:
#Scenario 2
a3=np.arange(9).reshape(3,3)
a4=np.arange(3).reshape(1,3)

print(a3)
print(a4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]]


In [97]:
a3+a4 #here array a4 consisting of one row will get summed with all three rows of array a3
#this is called broadcasting

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [98]:
#Rules of Broadcasting

In [99]:
a1=np.arange(3).reshape(1,3)
a2=np.arange(3).reshape(3,1) #same no of rows and columns so perform hoga operation

print(a1)
print(a2)

[[0 1 2]]
[[0]
 [1]
 [2]]


In [100]:
a1+a2

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [101]:
a3=np.arange(4).reshape(1,4)
a4=np.arange(12).reshape(3,4) #atleast same no of columns so perform hoga operation

print(a3)
print(a4)

[[0 1 2 3]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [102]:
a3+a4

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14]])

In [103]:
a5=np.arange(3).reshape(1,3)
a6=np.arange(16).reshape(4,4) #teeno disimilar hai lekin row one toh perform nahi hoga

print(a5)
print(a6)

[[0 1 2]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [104]:
# a5+a6 #error throw hoga

#abtak rule of thumb was if ek value 1 rahega and baaki 2 same rahenge toh run hoga

In [105]:
# if they are of diff dimensions but number are matching then operation will be performed
a7=np.arange(4)
a8=np.arange(20).reshape(5,4)

print(a7)
print(a8)
print("\n",a7+a8)

[0 1 2 3]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

 [[ 0  2  4  6]
 [ 4  6  8 10]
 [ 8 10 12 14]
 [12 14 16 18]
 [16 18 20 22]]


In [106]:
"""
Important Numpy functions
"""

'\nImportant Numpy functions\n'

In [109]:
np.random.random() #to generate random value

0.01011982124844335

In [110]:
np.random.seed(1) # with seed function i will get same random value
np.random.random()

0.417022004702574

In [117]:
np.random.uniform(1,100) #uniform values not middle values, uniform = distributed values)

67.37628350766182

In [116]:
np.random.uniform(1,100,10)

array([10.14152088, 19.43976093, 35.21051198, 40.27997995, 54.34285667,
       42.50025693, 68.83673054, 21.24077272, 87.9336262 ,  3.71137173])

In [120]:
np.random.randint(1,20)

18

In [121]:
np.random.randint(1,10,15).reshape(3,5)

array([[8, 1, 7, 8, 7],
       [2, 1, 2, 9, 9],
       [4, 9, 8, 4, 7]], dtype=int32)

In [126]:
a=np.random.randint(1,10,6)
a

array([3, 8, 8, 9, 7, 4], dtype=int32)

In [127]:
np.max(a)

np.int32(9)

In [128]:
np.min(a)

np.int32(3)

In [130]:
np.argmax(a) #index of max num in array

np.int64(3)

In [132]:
np.argmin(a) #gives index of min value

np.int64(0)

In [176]:
a=np.random.randint(1,10,6)
a

array([7, 6, 2, 3, 2, 6], dtype=int32)

In [179]:
a[a%2 != 0] = -1 # replace odd num with -1
a

array([-1,  6,  2, -1,  2,  6], dtype=int32)

In [185]:
a=np.random.randint(1,50,6)
a

array([14, 41, 15, 46, 24, 17], dtype=int32)

In [191]:
np.where(a%2 == 1,-1,a)  # without changing values of actual array 
# write this command in vairable to store value

array([14, -1, -1, 46, 24, -1], dtype=int32)

In [192]:
a # values are not changed

array([14, 41, 15, 46, 24, 17], dtype=int32)

In [194]:
a=np.random.randint(1,50,10)
a

array([36, 30, 34,  3, 21, 20, 49, 33, 29, 19], dtype=int32)

In [196]:
a=np.sort(a)
a

array([ 3, 19, 20, 21, 29, 30, 33, 34, 36, 49], dtype=int32)

In [201]:
np.percentile(a,25) #25 percent of my array is less than 20

np.float64(20.25)

In [202]:
np.percentile(a,50)

np.float64(29.5)

In [204]:
np.percentile(a,100)

np.float64(49.0)